server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
  routes:
    authentication:
      path: /auth/**
      serviceId: authentication
    projet:
      path: /projet/**
      serviceId: projet

