server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: projet
        uri: lb://projet
        predicates:
        - Path=/projet/**
        filters:
        - RewritePath=/projet/(?<path>.*), /$\{path}